apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment
  template:
    metadata:
      labels:
        app: sentiment
    spec:
      containers:
        - name: sentiment
          image: app-k8s:v1
          imagePullPolicy: Never  # Use local Kind image
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
